In [ ]:
# import numpy as np
# x = np.array([[2,5,8,9], [8,9,6,5]])
# x.shape

In [ ]:
# y = np.array(['a' , 'v' , 'x'])
# y

In [3]:
import numpy as np
x = np.array(5)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(type(x))

5
()
0
int32
<class 'numpy.ndarray'>


In [4]:
# type(x)
print(x.shape)
print(x.ndim)
x.dtype

()
0


dtype('int32')

In [20]:
my_arr = np.arange(45).reshape(9,5).astype('float')
print(my_arr)
print(my_arr.ndim)
# my_arr.astype('float')
# x = np.array([1,2,3] , dtype = 'float')
# x

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44.]]
2


In [24]:
arr_3d = np.arange(45).reshape(5,3,3)

print(arr_3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]]


In [5]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
a[0:7:2]

array([0, 2, 4, 6])

In [6]:
bg_array = np.arange(75).reshape(15 , 5)
bg_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [1]:
a[:7:2]

NameError: name 'a' is not defined

In [8]:
b = np.arange(24).reshape(6,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
bg_array

In [9]:
# b[start:end,start:end]
new_b = b[4:5,2:3]
print(new_b)
print(new_b.shape)
new_b.ndim

[[18]]
(1, 1)


2

In [11]:
assignment = np.arange(54).reshape(6,9)
assignment

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53]])

In [12]:
assignment[3:,5: ]

array([[32, 33, 34, 35],
       [41, 42, 43, 44],
       [50, 51, 52, 53]])

In [13]:
array_3d = np.arange(36).reshape(6,6)
array_3d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [14]:
array_3d[0:2,0:4]

array([[0, 1, 2, 3],
       [6, 7, 8, 9]])

In [ ]:
b = np.arange(27).reshape(3,3,3)
bb[1:2,0:1,0:1]
b.ndim

In [15]:
index = np.arange(36).reshape(6,6)
index

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [18]:
index[0:3,0:3] = 8
index

array([[ 8,  8,  8,  3,  4,  5],
       [ 8,  8,  8,  9, 10, 11],
       [ 8,  8,  8, 15, 16, 17],
       [18, 19, 20,  8, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [16]:
rep_3d = np.arange(27).reshape(3,3,3)
rep_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
rep_3d[1, 0:2, 2:] = 5
rep_3d

In [42]:
arr_3d = np.arange(27).reshape(3,3,3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [43]:
arr_3d[1:2,1:3,1:2]

array([[[13],
        [16]]])

In [45]:
assignment = np.arange(75).reshape(5,3,5)
assignment

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]],

       [[45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]]])

In [47]:
assignment[3,2,2] = 100
assignment

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14]],

       [[ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44]],

       [[ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56, 100,  58,  59]],

       [[ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]]])

In [61]:
x = np.ones((10,10))
x[1:9 , 1:9]= 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])