In [11]:
import numpy as np
a=np.arange(1,100,2)
print(a)

b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

d=np.zeros((3,4))
print(d)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
c=np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
e=np.random.random((2,2))
print(e)
data = np.random.randn(3, 4)
print(data)

[[0.44282219 0.28686067]
 [0.7545998  0.37991057]]
[[ 0.13815728 -1.36506272 -0.87910685 -0.90937522]
 [-1.08586746 -1.92510829  0.0152594   1.43434785]
 [ 1.40322421 -0.84596513  0.60508007 -1.24332861]]


In [13]:
g=np.full((2,2),7)
print(g)

[[7 7]
 [7 7]]


In [20]:
f=np.arange(2,1000)
j=np.arange(2,1000,5)
print(f)
print(j*2)



[  2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163
 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181
 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199
 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235
 236 237 238 239 240 241 242 243 244 245 246 247 24

In [19]:
import numpy as np 
ar=np.arange(14)
print(ar)
ar2 = ar.reshape(7,2)
print(ar2)
print(ar2.dtype)
print(ar2.size)
print(ar2.shape)
print(ar2.ndim)
print(type(ar2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]
int32
14
(7, 2)
2
<class 'numpy.ndarray'>


In [29]:
import numpy as np
ray = np.arange(1000).reshape(10,10,10)
print(ray)
%time for i in range(10): ray = ray * 2
print(ray)

[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]]

 [[100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]
  [150 151 152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189]
  [190 191 192 193 194 195 196 197 198 199]]

 [[200 201 202 203 204 205 206 207 208 209]
  [210 211 212 213 214 215 216 217 218 219]
  [220 221 222 223 224 225 2

In [47]:
import numpy as np
a = np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,20)])
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,20]])
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
print(a.dtype)
print(len(a))
print(a.astype(float))

print(b)
print(b.size)
print(b.shape)
print(b.ndim)
print(b.dtype)
print(len(b))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 20]]
12
(4, 3)
2
int32
4
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 20.]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 20]]
12
(4, 3)
2
int32
4


In [18]:
b = np.arange(1,101,2)
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [23]:
c = np.linspace(20,100,10)
c

array([ 20.        ,  28.88888889,  37.77777778,  46.66666667,
        55.55555556,  64.44444444,  73.33333333,  82.22222222,
        91.11111111, 100.        ])

In [39]:
d= np.zeros(10,10)


c=d.

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
c=np.full((3,3),3)
c

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [42]:
l=np.eye(5)
9l

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
g=np.random.random((2,2,5))
g

array([[[5.29186755e-01, 8.10047850e-01, 8.91312578e-01, 7.45399987e-01,
         6.42501698e-04],
        [1.30792273e-01, 6.85430635e-01, 3.24052685e-01, 5.10800353e-01,
         3.67882114e-01]],

       [[6.00246823e-01, 6.29459936e-01, 4.96125246e-01, 5.95593859e-01,
         4.36705986e-01],
        [5.79604760e-01, 9.53416196e-01, 7.79058492e-01, 1.63824145e-01,
         6.09387049e-01]]])

In [83]:
x = np.arange(100)
print(x.astype(float))
print(x)
x.tolist()


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [80]:
r=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
print(r.reshape(3,4))
print(r.resize(1,2))
print(r<5)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 11 12 13]]
None
[[ True  True]]


In [11]:
import numpy as np
x= np.random.random(100000000)
%time for i in range(10):z= x.sort()
print(z)


Wall time: 33.1 s
None


In [12]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [13]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)
#> array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [14]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)
#> (array([1, 3, 5, 7]),)

(array([1, 3, 5, 7], dtype=int64),)