In [4]:
import numpy as np
a= np.arange(100)
print(a)
print(type(a))
print (a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
<class 'numpy.ndarray'>
int32


In [9]:
b=np.array([[1,2,3],[3,2,4],[4,5,6],[6,7,8]])
print(b.reshape(3,4))
print(b)
c=np.ones((3,4))
print(c)
print(c.reshape(4,3))
print(c.size)
print(c.shape)
print(c.ndim)

[[1 2 3 3]
 [2 4 4 5]
 [6 6 7 8]]
[[1 2 3]
 [3 2 4]
 [4 5 6]
 [6 7 8]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
12
(3, 4)
2


In [17]:
list1 = [1,2,3,4,5,6,7,8,9,10]
c=np.array(list1,dtype=complex)
c.reshape(5,1,2,)

array([[[ 1.+0.j,  2.+0.j]],

       [[ 3.+0.j,  4.+0.j]],

       [[ 5.+0.j,  6.+0.j]],

       [[ 7.+0.j,  8.+0.j]],

       [[ 9.+0.j, 10.+0.j]]])

In [18]:
l=np.eye(3,3)
print(l.ndim)
print(l)

2
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
d=np.arange(100).reshape(2,25,1,2)
d.ndim
print(d)

[[[[ 0  1]]

  [[ 2  3]]

  [[ 4  5]]

  [[ 6  7]]

  [[ 8  9]]

  [[10 11]]

  [[12 13]]

  [[14 15]]

  [[16 17]]

  [[18 19]]

  [[20 21]]

  [[22 23]]

  [[24 25]]

  [[26 27]]

  [[28 29]]

  [[30 31]]

  [[32 33]]

  [[34 35]]

  [[36 37]]

  [[38 39]]

  [[40 41]]

  [[42 43]]

  [[44 45]]

  [[46 47]]

  [[48 49]]]


 [[[50 51]]

  [[52 53]]

  [[54 55]]

  [[56 57]]

  [[58 59]]

  [[60 61]]

  [[62 63]]

  [[64 65]]

  [[66 67]]

  [[68 69]]

  [[70 71]]

  [[72 73]]

  [[74 75]]

  [[76 77]]

  [[78 79]]

  [[80 81]]

  [[82 83]]

  [[84 85]]

  [[86 87]]

  [[88 89]]

  [[90 91]]

  [[92 93]]

  [[94 95]]

  [[96 97]]

  [[98 99]]]]


In [5]:
k=np.arange(40).reshape(4,2,5)
print(k)


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]]


In [9]:
print(k[0][:][3:])

[]


In [1]:
w=np.array([[1,2,3],[4,5,6]])
print(w[0:2,0:2])

NameError: name 'np' is not defined